spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3307/tickup
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root123
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect